import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';

const root=new URL('../',import.meta.url).pathname.replace(/^\/(.:)/,'$1');
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.json':'application/json','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const server=createServer(async(req,res)=>{try{const clean=decodeURIComponent((req.url||'/').split('?')[0]);if(clean==='/favicon.ico'){res.writeHead(204);return res.end()}const file=normalize(join(root,clean==='/'?'index.html':clean));if(!(await stat(file)).isFile())throw 0;res.writeHead(200,{'content-type':mime[extname(file)]||'application/octet-stream'});res.end(await readFile(file))}catch{res.writeHead(404);res.end('not found')}});
await new Promise(r=>server.listen(4177,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||undefined});
const page=await browser.newPage({viewport:{width:1279,height:599}}),errors=[];
page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://127.0.0.1:4177/',{waitUntil:'domcontentloaded'});
const catalog=await page.evaluate(()=>{const profiles=window.hyCards.map(c=>window.hyManifestFx(c));return{cards:window.hyCards.length,profiles:profiles.length,unique:new Set(profiles.map(x=>x.signature)).size,motifs:new Set(profiles.map(x=>x.motif)).size,entrances:new Set(profiles.map(x=>x.entrance)).size,cameras:new Set(profiles.map(x=>x.camera)).size,valid:profiles.every(x=>x.sigil&&x.primary&&x.accent&&x.duration>=900&&x.duration<=1250&&x.particles>=10)}});
const party=await page.evaluate(()=>window.hyCards.slice(0,5).map((c,slot)=>({id:c.id,name:c.name,img:new URL(c.img,location.href).href,finalImg:new URL(c.finalImg,location.href).href,stage:6,manifested:slot===0,role:c.role,faction:c.faction,route:c.route,skill:c.skill,cost:1,slot,manifestFx:c.manifestFx})));
await page.goto('http://127.0.0.1:4177/admin/dungeon-flow.html?region=yeoja&v=79.0.0',{waitUntil:'networkidle'});
await page.evaluate(()=>localStorage.setItem('hy-dungeon-flow-v660',JSON.stringify({yeoja:{routeDone:true,investigationComplete:true,clueStates:[0,1,2].map(()=>({observed:true,verified:true,recorded:true,confidence:3})),zones:[0,1,2,3,4,5,6],bossSeen:true,complete:false}})));
await page.reload({waitUntil:'networkidle'});
await page.evaluate(p=>window.postMessage({type:'hy-journey-context',companionCard:p[0].id,companionName:p[0].name,companionRole:`${p[0].faction} · ${p[0].role}`,companionStage:6,companionManifested:true,companionImg:p[0].img,companionFinalImg:p[0].finalImg,companionSkill:p[0].skill,companionManifest:`${p[0].name} · 최종현현`,companionManifestFx:p[0].manifestFx,party:p,motion:true},location.origin),party);
await page.locator('#confirmBoss').click();
await page.locator(`[data-card="${party[0].id}"]`).last().click();
await page.waitForTimeout(120);
const live=await page.evaluate(()=>{const m=document.querySelector('#seventhSkillMotion'),p=document.querySelectorAll('#manifestParticles i'),b=document.querySelector('#skillBanner');return{playing:m?.classList.contains('play'),signature:m?.dataset.signature,motif:m?.dataset.motif,entrance:m?.dataset.entrance,camera:m?.dataset.camera,particles:p.length,technique:document.querySelector('#manifestTechnique')?.textContent,cardArt:document.querySelector('#seventhSkillCard')?.getAttribute('src'),sigil:document.querySelector('#seventhSkillSigil')?.textContent,cameraClass:[...document.querySelector('#game').classList].some(x=>x.startsWith('manifest-camera-')),bannerPresent:!!b}});
const report={version:'79.0.0',catalog,live,errors,pass:catalog.cards===125&&catalog.profiles===125&&catalog.unique===125&&catalog.motifs>=7&&catalog.entrances===6&&catalog.cameras===5&&catalog.valid&&live.playing&&live.signature===party[0].manifestFx.signature&&live.motif===party[0].manifestFx.motif&&live.particles===party[0].manifestFx.particles&&live.technique===party[0].skill&&!!live.cardArt&&!!live.sigil&&live.cameraClass&&live.bannerPresent&&!errors.length};
console.log(JSON.stringify(report));
await browser.close();server.close();if(!report.pass)process.exit(1);
